version: '3'

services:
  run_recommendation_1:
    image: sisinflabpoliba/mm-recsys
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=.
      - CUBLAS_WORKSPACE_CONFIG=:16:8
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    command: bash -c "nvidia-smi && git pull && python3.11 run_split.py && python3.11 run_benchmarking.py --setting 1"
    volumes:
      - ../Ducho/local/data/demo_recsys:/Formal-Multimod-Rec/data/baby
      - ./results:/Formal-Multimod-Rec/results
  run_recommendation_2:
    image: sisinflabpoliba/mm-recsys
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=.
      - CUBLAS_WORKSPACE_CONFIG=:16:8
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    command: bash -c "nvidia-smi && git pull && python3.11 run_split.py && python3.11 run_benchmarking.py --setting 2"
    volumes:
      - ../Ducho/local/data/demo_recsys:/Formal-Multimod-Rec/data/baby
      - ./results:/Formal-Multimod-Rec/results
  run_recommendation_3:
    image: sisinflabpoliba/mm-recsys
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=.
      - CUBLAS_WORKSPACE_CONFIG=:16:8
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    command: bash -c "nvidia-smi && git pull && python3.11 run_split.py && python3.11 run_benchmarking.py --setting 3"
    volumes:
      - ../Ducho/local/data/demo_recsys:/Formal-Multimod-Rec/data/baby
      - ./results:/Formal-Multimod-Rec/results
