experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.txt
    validation_path: ../data/{0}/val.txt
    test_path: ../data/{0}/test.txt
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/image_feat
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/text_feat
  dataset: office
  top_k: 20
  evaluation:
    cutoffs: [ 10, 20 ]
    simple_metrics: [ Recall, nDCG, EFD, Gini, APLT, ItemCoverage ]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.BPRMF:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      epochs: 200
      factors: 64
      batch_size: 1024
      l_w: [ 1e-5, 1e-2 ]
      seed: 123
    external.NGCF:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      epochs: 200
      factors: 64
      batch_size: 1024
      n_layers: 3
      weight_size: 64
      node_dropout: 0.1
      message_dropout: 0.1
      normalize: True
      l_w: [ 1e-5, 1e-2 ]
      seed: 123
    external.LightGCN:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      epochs: 200
      n_layers: 3
      factors: 64
      batch_size: 1024
      normalize: True
      l_w: [ 1e-5, 1e-2 ]
      seed: 123
    external.LightGCNM:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      epochs: 200
      n_layers: 3
      factors: 64
      batch_size: 1024
      normalize: True
      aggregation: mean
      modalities: ('visual','textual')
      loaders: ('VisualAttribute','TextualAttribute')
      l_w: [ 1e-5, 1e-2 ]
      seed: 123
    external.SGL:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      epochs: 200
      batch_size: 1024
      factors: 64
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      l_w: [ 1e-5, 1e-2 ]
      n_layers: 3
      ssl_temp: 0.2
      ssl_reg: 0.1
      ssl_ratio: 0.1
      sampling: ed
      seed: 123