experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_indexed.tsv
    validation_path: ../data/{0}/val_indexed.tsv
    test_path: ../data/{0}/test_indexed.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/visual_embeddings_indexed/tensorflow/ResNet50/avg_pool
  dataset: music
  top_k: 50
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG, Precision, HR, APLT, ACLT, ARP, single_nDCG, single_ARP]
    complex_metrics:
      - metric: clustered_Recall
        user_clustering_name: WarmColdUsers
        user_clustering_file: ../data/music/rilassamento_indexed.tsv
      - metric: clustered_nDCG
        user_clustering_name: WarmColdUsers
        user_clustering_file: ../data/music/rilassamento_indexed.tsv
      - metric: clustered_APLT
        user_clustering_name: WarmColdUsers
        user_clustering_file: ../data/music/rilassamento_indexed.tsv
      - metric: clustered_ACLT
        user_clustering_name: WarmColdUsers
        user_clustering_file: ../data/music/rilassamento_indexed.tsv
      - metric: clustered_ARP
        user_clustering_name: WarmColdUsers
        user_clustering_file: ../data/music/rilassamento_indexed.tsv
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.VBPR:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 190
        validation_metric: Recall@20
        restore: False
      lr: 0.005
      modalities: ('visual',)
      loaders: ('VisualAttribute',)
      epochs: 190
      factors: 64
      batch_size: 1024
      l_w: 1e-2
      comb_mod: concat
      seed: 123
